### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by Aspie96** [sxw-js/sxw-js#20]
Maybe multiple languages shuld be supported?

**Comment by Aspie96** [comment]
I close the issue: given how small the library is, providing support for multiple languages would be unreasonable.
That unless the user is allowed to download the library with support for some specific languages, but that would require the library to be generated on the spot. This is doable and actually not hard, but it would require a radical change. Thus I close the issue for now.

**Comment by kolappannathan** [comment]
@Aspie96 This is good feature request. I will implement it.
